# Generated by Django 6.0 on 2026-01-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attending',
            name='attending_as',
        ),
        migrations.RemoveField(
            model_name='attending',
            name='bulk_reg',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Attending',
        ),
    ]
