# Generated by Django 5.2 on 2025-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
