# Generated by Django 6.0 on 2026-01-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_attending_attending_as_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_types', to='app.bulk_event_reg')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
            ],
        ),
    ]
