# Generated by Django 5.2 on 2025-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_announcement_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='eventbanner/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='banner',
            field=models.ImageField(upload_to='announcementbanner/'),
        ),
    ]
