# Generated by Django 6.0 on 2026-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_roles_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='roles',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
