# Generated by Django 6.0 on 2026-01-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attending_roles_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='attending',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
    ]
