# Generated by Django 5.2 on 2025-04-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_banner_alter_announcement_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='proof_of_payment',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_payment', models.FileField(upload_to='payments/')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.member')),
                ('membertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membertypes', to='app.membertype')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_year')),
            ],
        ),
    ]
