# Generated by Django 5.2 on 2025-04-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_member_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='status',
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.member'),
        ),
    ]
