# Generated by Django 6.0 on 2026-01-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_attending_roles_delete_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='bulk_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bulk_event_reg'),
        ),
    ]
