# Generated by Django 5.2 on 2025-04-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_membership_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membertype',
        ),
    ]
