# Generated by Django 6.0 on 2026-01-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_attending_bulk_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attending',
        ),
    ]
