# Generated by Django 5.2 on 2025-04-29 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='membertype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='officertype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salutation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='school_year',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
