# Generated by Django 5.2 on 2025-04-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_membershiptype_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.membertype'),
            preserve_default=False,
        ),
    ]
