# Generated by Django 5.2 on 2025-04-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_member_membertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membertype',
        ),
    ]
