# Generated by Django 5.2.6 on 2026-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_evaluation_nps_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
