# Generated by Django 5.2 on 2025-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_member_membertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
