# Generated by Django 5.2.6 on 2026-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
