# Generated by Django 5.2 on 2025-08-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_member_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_type',
        ),
    ]
