# Generated by Django 5.2.6 on 2026-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_membership_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_dpa_check',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
