# Generated by Django 5.2.6 on 2026-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_member_is_dpa_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='president',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
