# Generated by Django 5.2 on 2025-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_member_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
