# Generated by Django 5.2.6 on 2026-06-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_organization_president'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit_Insti_Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_year')),
            ],
        ),
    ]
