# Generated by Django 5.2 on 2025-09-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_school_year_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
