# Generated by Django 5.2.6 on 2026-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_limit_insti_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_treasurer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
