# Generated by Django 5.2 on 2025-09-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_school_year_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school_year'),
        ),
    ]
