# Generated by Django 5.2.6 on 2026-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_member_is_treasurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_treasurer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_treasurer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
