# Generated by Django 5.2 on 2025-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Set whether the event is active or inactive', max_length=8),
        ),
    ]
