# Generated by Django 5.2.6 on 2026-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_invitation_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_areacoor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_auditor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_secretary',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
