# Generated by Django 5.2 on 2025-09-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_event_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegistration',
            new_name='MemberEventRegistration',
        ),
    ]
