# Generated by Django 5.2 on 2025-09-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_eventregistration_membereventregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberEventRegistration',
            new_name='Member_Event_Registration',
        ),
    ]
