# Generated by Django 5.2.6 on 2026-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_customuser_is_areacoor_customuser_is_auditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
