# Generated by Django 5.2.6 on 2026-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
