# Generated by Django 5.2 on 2025-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_membereventregistration_member_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('full', 'Full')], default='active', help_text='Set whether the event is active or inactive', max_length=8),
        ),
    ]
