# Generated by Django 5.2.6 on 2026-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_membership_or_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('amt_paid', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
