# Generated by Django 5.2 on 2025-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
