# Generated by Django 5.2 on 2025-09-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_event_registered_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registered_attendees',
            new_name='available_slots',
        ),
    ]
