# Generated by Django 5.2.6 on 2025-09-22 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_registered_attendees_event_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school_year'),
        ),
    ]
