# Generated by Django 5.2 on 2025-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_registered_attendees_event_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
