# Generated by Django 5.2.6 on 2026-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_invoice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.CharField(max_length=100),
        ),
    ]
