# Generated by Django 5.2.6 on 2025-10-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_membership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='school_year',
        ),
    ]
