# Generated by Django 5.2.6 on 2025-11-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_membershiptype_processed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='membership',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
