# Generated by Django 5.2.6 on 2025-11-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tags'),
        ),
    ]
