# Generated by Django 5.2.6 on 2025-11-25 15:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_event_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('member_event_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member_event_registration')),
            ],
        ),
    ]
