# Generated by Django 5.2.6 on 2025-11-25 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_event_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_event_registration',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AlterField(
            model_name='member_event_registration',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
