# Generated by Django 5.2.6 on 2025-11-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_member_event_registration_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_event_registration',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='member_event_registration',
            old_name='user_id',
            new_name='user',
        ),
    ]
