# Generated by Django 5.2.6 on 2025-12-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_paritcipant_type_participation_type_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'officer'), ('3', 'member'), ('4', 'institution')], max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Set whether the event is active or inactive', max_length=8),
        ),
    ]
