# Generated by Django 5.2.6 on 2025-12-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_event_is_full_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Attendance',
        ),
    ]
