# Generated by Django 5.2.6 on 2025-12-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_event_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_event_registration',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
