# Generated by Django 5.2.6 on 2025-12-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_member_event_registration_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paritcipant_type',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paritcipant_type',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='participation_type',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='participation_type',
            name='updated_at',
        ),
    ]
