# Generated by Django 5.2.6 on 2025-12-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_paritcipant_type_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
