# Generated by Django 5.2.6 on 2025-12-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_competition_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk_event_reg',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='bulk_event_reg',
            name='participant_type',
        ),
        migrations.RemoveField(
            model_name='bulk_event_reg',
            name='participation_type',
        ),
        migrations.RemoveField(
            model_name='bulk_event_reg',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='bulk_event_reg',
            name='email',
        ),
        migrations.AddField(
            model_name='bulk_event_reg',
            name='if_coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bulk_event_reg',
            name='if_competitor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bulk_event_reg',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulk_event_reg',
            name='is_competiror',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Paritcipant_Type',
        ),
        migrations.DeleteModel(
            name='Participation_Type',
        ),
    ]
