# Generated by Django 5.2.6 on 2025-12-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_bulk_event_reg_competition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulk_event_reg',
            old_name='middle_name',
            new_name='middle',
        ),
    ]
