# Generated by Django 5.2.6 on 2025-12-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_middle_name_bulk_event_reg_middle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulk_event_reg',
            old_name='contact_no',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='bulk_event_reg',
            old_name='is_competiror',
            new_name='is_competitor',
        ),
    ]
