# Generated by Django 6.0 on 2025-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_contact_no_bulk_event_reg_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk_event_reg',
            name='attending_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
