# Generated by Django 6.0 on 2025-12-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_bulk_event_reg_attending_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk_event_reg',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
