# Generated by Django 6.0 on 2025-12-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_bulk_event_reg_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk_event_reg',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.member'),
        ),
    ]
