# Generated by Django 6.0 on 2025-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_bulk_event_reg_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk_event_reg',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulk_event_reg',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member_event_registration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
