# Generated by Django 6.0 on 2025-12-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_bulk_event_reg_is_approved_bulk_event_reg_is_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='template_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
