# Generated by Django 6.0 on 2025-12-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_event_template_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_event_registration',
            name='user',
        ),
        migrations.AddField(
            model_name='member_event_registration',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.member'),
        ),
    ]
