# Generated by Django 6.0 on 2025-12-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_member_event_registration_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending_as',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
